### ISSUE TITLE
Budget runs low

### ISSUE THREAD

**Issue by antsy** [underkround/steamfilter-backend#1]
This project's month-to-date costs have gone up by 5007% over the last month.

-- Love, your financial officer.

**Comment by murgo** [comment]
But how much? Do we need to take the project to a server?

la 2. maalisk. 2019 klo 13.24 Antti Humalamäki <notifications@github.com>
kirjoitti:

**Comment by antsy** [comment]
Friends don't let friends run their own data centers.
